### ISSUE TITLE
SemanticSearch.py tokenizers.tokenizers error+해결과정공유

### ISSUE THREAD

**Issue by hyehyeonmoon** [BM-K/KoSentenceBERT_SKT#6]
안녕하세요, 좋은 코드를 공유해주셔서 감사합니다.

다름이 아니라 SemanticSearch.py를 실행하면서 tokenizers.tokenizers 오류가 났습니다.  
다른 분들이 올리신 이슈에 따라 tokenizers __init__.py를 수정하기도 하고, requirements.txt에 있는 transformers==2.8.0 을 실행하지 않고 transformers 폴더를 site-packages에 넣기만 했는데도 해결되지 않아 이슈 드립니다.

- os : window 10
- anaconda
- python 3.7

모든 절차를 그대로 따라했고, sentence_transformers, tokenizers, transformers 모두 site-packages로 이동했습니다. 

![캡처](https://user-images.githubusercontent.com/55529617/127757856-f45b50be-39f8-4331-9a91-4cbbc3c93e0f.PNG)
![image](https://user-images.githubusercontent.com/55529617/127757948-cfdfbc3e-1e5d-49a6-a9a1-696d9b13a6a4.png)

**Comment by BM-K** [comment]
tokenizers 모듈이 없는 것 같은데, transformer를 downgrade나 upgrade하시고 site-packages에 옮겨 보시겠어요?

**Comment by fenneccat** [comment]
tokenizers 모듈을 git에 올라와있는 것을 site-packages로 옮겼는데 위 에러가 납니다.  transformer도 git에 올라와있는 것을 옮겼는데, git에 올라와있는 directory말고 transformer를 다시 받아야하나요?

**Comment by hyehyeonmoon** [comment]
답변 감사드립니다. 한 가지 여쭙고 싶은 게 requirements.txt에 transformers==2.8.0인 것을 확인했는데 여기서 downgrade 또는 upgrade를 한 뒤에 transformers 폴더를 site-packages에 옮기면 되는 걸까요..?

![image](https://user-images.githubusercontent.com/55529617/129467929-0e4651a5-5f2f-411f-be16-17aecae17594.png)

**Comment by hyehyeonmoon** [comment]
## 이슈 해결했습니다.

다른 분들께 SemanticSearch.py 실행을 위해 생긴 오류들을 어떻게 해결했는지 과정을 공유하고자 기록합니다.

다시 한 번 좋은 코드 공유해주셔서 감사하며 문제는 코드가 아닌 저 자신에게 있다는 걸 다시금 깨닫습니다.
(위의 코멘트는 리눅스에서 mv를 사용할 때 directory를 위와 같이 지정할 경우 엉뚱한 곳에 이동되어진다는 것을 알았습니다.)

로컬에서 환경을 구축하고자 했지만 버전 호환이 되지 않아

결국 docker image를 사용했습니다. 

### 환경
환경 : mac m1
도커 : silicon 전용
비쥬얼 스튜디오 코드와 연동

### 명령어

터미널을 열어서 아래 명령어들을 모두 차례대로 쳐 줍니다.
```
docker pull --platform linux/amd64 klbm126/kosbert_image:latest //--platform linux/amd64 는 m1에 해당하는 옵션입니다
docker run --rm -it --name=kosbert_image klbm126/kosbert_image:latest

git clone https://github.com/SKTBrain/KoBERT.git
cd KoBERT
pip install -r requirements.txt
pip install .
cd ..
git clone https://github.com/BM-K/KoSentenceBERT_SKTBERT.git
cd KoSentenceBERT_SKTBERT
pip install -r requirements.txt

// 터미널에서 리눅스 명령어를 사용해 파일을 옮기는 것이 어려워 GUI를 이용했습니다
// 저는 visual studio code와 연동해 직접 파일을 옮겼습니다 [참고사이트](https://curioso365.tistory.com/100)
// 덮어쓰기와 병합하기 무엇을 선택할지 정말 고민했는데 덮어쓰기 해도 됩니다.
// 옮길 경우 기존의 opt/conda/lib/python3.7/site-packages/sentence_transformer 를 삭제하시고 github의 sentence_transformer 폴더를 옮겨주세요. 아닐 경우  sentence_transformer copy 이런 형태로 저장되기 때문에 이름을 변경해 주셔야 합니다. 
//KoSentenceBERT_SKTBERT폴더 내의 옮긴 폴더들(transformer, tokenizers, sentence_transformers) 삭제하기

// 이유는 모르겠으나 아래 라이브러리가 설치가 안 되서 저는 수동으로 설치해 주었습니다.
pip install gluonnlp
pip install mxnet

```
### 추가 설정

아직 끝나지 않았습니다.

몇 가지 설정을 더 해주셔야 합니다.

1. 학습된 pt 파일 옮기기

README를 보시면 학습된 pt 파일을 드라이브에서 다운받아 output/training_sts/0_Transformer/result.pt 식으로 저장하라고 되어 있습니다. 
(연동된 visual studio code에 다운받은 result.pt를 해당 폴더에 드래그 앤 드랍 하시면 자동으로 컨테이너에 적용이 됩니다.)

2. GPU가 없을 때

저는 컴퓨터에 GPU가 없습니다. 코드는 기본적으로 GPU 기반이기 때문에 오류가 나며 [해당이슈](https://github.com/BM-K/KoSentenceBERT_SKT/issues/8) closed issue에서 이를 해결하고 있습니다. 가장 마지막 코멘트 그대로 따라하시면 해결이 됩니다.  
(참고로 저도 SentenceTransformer(model_path, device='cpu') 만 해주었을 때는 작동이 안 됬습니다.)

3. docker killed 오류(out of memory)

이제 SemanticSearch.py를 실행하면 killed 오류가 납니다. [오류해결](https://stackoverflow.com/questions/44417159/docker-process-killed-with-cryptic-killed-message) answer 중 첫 번재 docker dashboard에서 설정(톱니바퀴)에 들어가셔서 Resources 탭에서 Memory 용량을 2G(default)에서 더 늘리시면 됩니다.  

이제 드디어 

```
python SemanticSearch.py
```

성공!  
하고나서 컨테이너를 바로 닫으시면 안 되고 꼭 commit 해 주셔야 합니다! [참고사이트](https://nicewoong.github.io/development/2018/03/06/docker-commit-container/)
(다른 터미널을 여셔서 그곳에서 현재 실행 중인 container의 상태를 commit 할 수 있습니다.)

그러면 image 크기만 10.3G에 다다르는 여정이 끝이 납니다^^

**Comment by fenneccat** [comment]
로컬에서 tokenizers.tokenizers에러는 결국 해결이 안되셨나요?
어떻게 어떻게 해결해가지고 사용했었는데 실수로 해당 환경을 지우고나서 다시 재구축이 안되네요...

**Comment by d10000usd** [comment]
설치되서 사용하시나요????

.json 파일들 없다고 나오는데... 몇시간째 삽질 중인데.요

**Comment by BM-K** [comment]
@d10000usd https://github.com/BM-K/Sentence-Embedding-is-all-you-need/tree/main/KoSBERT
위 레파지토리 사용하시는 것을 추천드립니다.

**Comment by hyehyeonmoon** [comment]
저도 얼마 전에 다시 만들려고 하다가 재구축이 안되서 이전에 사용한 image 그대로 가져다 썼습니다. (재구축이 안 되는 이유가 얼마 전 SKT_KoBERT 업데이트가 이루어져서라고 짐작은 하는데 위에 올려주신 링크로 저도 다시 한 번 해봐야겠네요)
이 이미지는 라이브러리 폴더 옮기는 것, .pt 파일, 설치 모두 되어 있어서 용량이 좀 큽니다. 감안해서 사용해주세요.
제가 프로젝트용으로 만든 것이라 github 파일들이랑 완전 똑같지는 않고 모델만 똑같습니다. 감안해서 직접 cp 해서 사용하시면 될 것 같아요!

docker image 다운로드:bookbug/kosbert_image:latest
(참고 : CPU로 실행되도록 설정되어 있습니다. GPU로 실행하고 싶으시다면 이슈에서 [GPU 실행](https://github.com/BM-K/KoSentenceBERT-SKT/issues/8)을 참고해주세요.)
(참고 : dockerfile로 작성하면 빌드되도 모델 실행 안됩니다. 제가 시도해봤는데 안되서 현재 해결중입니다)
```
// cpu 실행시 
docker run --rm -it -p [로컬 연결포트]:[docker 연결포트] --name=kosbert_image bookbug/kosbert_image:latest 

//gpu 실행시 
docker run --gpus all --rm -it -p [로컬 연결포트]:[docker 연결포트] --name=kosbert_image bookbug/kosbert_image:latest 

cd /workspace/KoSentenceBERT_SKTBERT
// 모델 실행하면 정상적으로 실행 됩니다
```

**Comment by d10000usd** [comment]
hyehyeonmoon  ~ thanks

도커이미지 받아서 모델 런까지 확인 했어요. ~
플라스크 파일 없었으면 바로 지울려고 하다가 
약간 수정하니까 터미널에서 모델 돌아 가네요.

런타임이 길기는 한데 일단은 딱 필요한 부분까지 돌아가서 다행이에요.
다른건 시간이 필요할 뜻 하고. 


BM-K  ~ thanks
링크 고맙습니다. 
딱 필요한걸 걸어 주셨어요.  ~ 튜닝할때 잘쓸께요.
:)

**Comment by z9612** [comment]
말씀해주신대로 진행했는데도 No module named 'kobert' 가 자꾸 뜨는데 무슨 문제일까요 ㅜㅜ

**Comment by d10000usd** [comment]
도커이미지 받아서 돌리면 사용 가능해요.
급한거면 hyehyeonmoon 님이 걸어두신 도커 받으셔서 테스트 해보세요. mac m1에서도 돌아 가요.

경로, 데이터 복사 설정 처음 하실때 잘못 하면 고치는게 어렵더라구요.

도커 이미지 받아서 그대로 쓰는게 시간 절약 됩니다

**Comment by z9612** [comment]
저는 python SemanticSearch.py 를 사용해보고 싶은데 만들어진 'bookbug/kosbert_image:latest' 이미지를 사용 했을 경우에 app.py를 실행할 수 있던데 이 친구를 실행하고 나면 특정 아이피:포트로 열라고 되있더라구요.. 이걸 브라우저로 요청하니까 타임아웃이 뜨던데 원래 이렇게 쓰는거 맞을까요?

**Comment by d10000usd** [comment]
app.py 는 무시하셔도 됩니다. 
지금 다시 돌려 봤는데요.( bookbug/kosbert_image:latest' )
app.py  위치에, 새파일  test.py 만들고

BM-K 링크예제 
Semantic Search 예제 붙여 넣으시면 돌아 갈거에요. 아래 처럼 모델 케쉬 한후 실행 됩니다. 

~~~
using cached model
using cached model
using cached model
Load Model
~~~~

**Comment by z9612** [comment]
으앗 말씀대로 하니 잘되네요 @d10000usd 님 정말 감사드립니다..! 애꿎은 .ipynb 파일이랑 app.py 만 만지작 대고 있었네요 😥
튜토리얼부터 이렇게 막히다니 험난하군요 😅
