### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Haebuk** [BM-K/KoSentenceBERT_SKT#9]
안녕하세요.
README에 있는 sts pre-trained 모델을 사용하려고 합니다.

그러나 `FileNotFoundError: [Errno 2] No such file or directory: './KoSentenceBERT_SKT/output/training_sts/0_Transformer/result.pt'` 에러가 발생합니다.

깃허브에 있는  output/training_sts에는 0_transformer 폴더가 존재하지 않습니다.
단순히 0_transformer 폴더만 만들면 될까요?

**Comment by BM-K** [comment]
단순히 0_transformer 폴더만 만들면 될까요?
 >> 네

**Comment by Haebuk** [comment]
감사합니다.

**Comment by Haebuk** [comment]
@BM-K 
`FileNotFoundError: [Errno 2] No such file or directory: './KoSentenceBERT_SKT/output/training_sts/0_Transformer\\sentence_bert_config.json'`

다른 파일이 없다고 나옵니다.
